gitlabUrl: https://gitlab.com/
kind: Runner
runnerRegistrationToken: ${runnerRegistrationToken}   # a new runner, you can specify runnerRegistrationToken
# runnerToken: ${runnerToken}  // To register an existing runner, you can use runnerToken
name: gitlab-runner
unregisterRunners: true
terminationGracePeriodSeconds: 3600
secret: gitlab-runner
rbac:

  create: true
  resources: ["pods", "pods/exec", "secrets"]
  verbs: ["get", "list", "watch", "create", "patch", "delete"]
  clusterWideAccess: false
  podSecurityPolicy:
    enabled: false
    resourceNames:
    - gitlab-runner
runners:
  config: |
    [[runners]]
      [runners.kubernetes]
        image = "ubuntu:16.04"
  privileged: true
