renovate:
    config: |
        {
            "platform": "${platform}",
            "endpoint": "${endpoint}",
            "token": "${token}",
            "autodiscover": "${autodiscover}",
        }
